### ISSUE TITLE
Where should I import ParallaxConfig?

### ISSUE THREAD

**Issue by dmitry-grinko** [MattJeanes/ngx-parallax#11]
It's not clear documentation. Where should I import ParallaxConfig?

**Comment by AmyJeanes** [comment]
The parallax config is optional, it's purpose is to allow you to have type checking on the binding `<div parallax [config]="thisThing">` in your component but otherwise unneeded, only need to import the module to get it working

**Comment by dmitry-grinko** [comment]
I know it's optional. Should I add it to component?
import { ParallaxConfig } from 'ngx-parallax';

**Comment by AmyJeanes** [comment]
If you like, you would do this in your component:

`public thisThing: ParallaxConfig`

**Comment by dmitry-grinko** [comment]
thanks!
