### ISSUE TITLE
Config changes not updating the view

### ISSUE THREAD

**Issue by bostondevin** [MattJeanes/ngx-parallax#13]
If I set the config parameters (initialValue, ratio) equal to a variable, then change that variable with another component, the parameters don't update in the view. Is there a way for you to listen to changes in the config and then make the view updates?

**Comment by bostondevin** [comment]
It works fine if I use the individual parameters on the directive

**Comment by AmyJeanes** [comment]
Yeah that'll be angular change detection, if you replace the entire config object it'd pick it up too
