### ISSUE TITLE
add @Directive annotation in parallax.directive.d.ts

### ISSUE THREAD

**Issue by nasserghiasi** [MattJeanes/ngx-parallax#2]
add @Directive annotation in parallax.directive.d.ts
angular cli compiler error:
ERROR in : Unexpected value 'Parallax in /path/node_modules/ngx-parallax/lib/parallax.directive.d.ts' declared by the module 'MainModule in /path/src/app/modules/main/main.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by AmyJeanes** [comment]
Hello, I don't use angular cli so would you be able to post some quick instructions on how I would get this error? If you know how to fix it yourself a PR would be appreciated! Thanks

**Comment by nasserghiasi** [comment]
ok, I will send pull request
