### ISSUE TITLE
parallax examples

### ISSUE THREAD

**Issue by webspecialist** [MattJeanes/ngx-parallax#3]
Do you have any examples?
Page of https://mattjeanes.com/ngx-parallax/ts-examples
didn't work it show server error 
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

Would you fix it, please?

**Comment by AmyJeanes** [comment]
Where'd you find that link? It should be http://cwadrupldijjit.com/ng2-parallax/ts-examples

**Comment by webspecialist** [comment]
oh ok thanks

**Comment by dm-grinko** [comment]
http://cwadrupldijjit.com/ng2-parallax/ts-examples is not working

**Comment by AmyJeanes** [comment]
Oh dear, looks like the original authors site has gone down - not much I can do, you can try and contact the guy if you like.
