### ISSUE TITLE
add @NgModule decorator to ParallaxModule

### ISSUE THREAD

**Issue by GeorgeKnap** [MattJeanes/ngx-parallax#7]
error in `@angular/cli 6.0.0` prod build:

`ERROR in : Unexpected value 'ParallaxModule in E:/Development/profile-web/node_modules/ngx-parallax/lib/parallax.module.d.ts' imported by the module 'AppModule in E:/Development/profile-web/src/app/app.module.ts'. Please add a @NgModule annotation.`

add `@NgModule` decorator to fix the issue.

**Comment by bostondevin** [comment]
+1

**Comment by AmyJeanes** [comment]
I thought I already added support for this:

https://github.com/MattJeanes/ngx-parallax/blob/master/lib/parallax.module.ts

**Comment by AmyJeanes** [comment]
Sorry, pressed send too early - if I'm doing something wrong can someone please submit a PR that fixes it? I'll be happy to merge/publish

**Comment by matbalazsi** [comment]
+1

**Comment by AmyJeanes** [comment]
This should be resolved in `4.0.0` - let me know if it doesn't work!
